version: 2
enable-beta-ecosystems: true
updates:
  # Default Cooldown (60 days)   
  - package-ecosystem: "composer"
    open-pull-requests-limit: 16
    directory: "/cooldown-default"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 60

  # Semver Major Cooldown (60 days)
  - package-ecosystem: "composer"
    open-pull-requests-limit: 16
    directory: "/cooldown-major"
    schedule:
      interval: "daily"
    cooldown:
      semver-major-days: 60

   # Semver Minor Cooldown (60 days)
  - package-ecosystem: "composer"
    open-pull-requests-limit: 14
    directory: "/cooldown-minor"
    schedule:
      interval: "daily"
    cooldown:
      semver-minor-days: 60

  # Semver Patch Cooldown (60 days)
  - package-ecosystem: "composer"
    open-pull-requests-limit: 14
    directory: "/cooldown-patch"
    schedule:
      interval: "daily"
    cooldown:
      semver-patch-days: 60


  # Cooldown with Mixed Inclusion/Exclusion
  - package-ecosystem: "composer"
    open-pull-requests-limit: 14
    directory: "/cooldown-mixed"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 60
      include:
        - "phpunit/phpunit"
        - "mockery/mockery"
        - "squizlabs/php_codesniffer"
      exclude:
        - "friendsofphp/php-cs-fixer"
        - "fakerphp/faker"
    
